
const headers = [
    'KEY',
    'Carrier',
    'Origin',
    'Destination',
    'Aircraft Type',
    'Flt Number',
    'Time Zone',
    'STD',
    'STA',
    'Duration',
    'LAT',
    'TOA',
    'Capacity Unit',
    'Remaining Capacity',
    'Type',
    'Currency Rates',
    'Minimum',
    'Weight Type',
    'Weight Break',
    'Rate',
    'Weight Break 2',
    'Rate 2',
    'Weight Break 3',
    'Rate 3',
    'Weight Break  4',
    'Rate 4',
    'Weight Break 4',
    'Rate 4',
    'Currency Surcharges',
    'Surcharge Fuel',
    'Surcharge Security',
    'Surcharges Others Type',
    'Surcharges Others'
]

module.exports = headers